name: npm test
on: 
  workflow_dispatch:
               
jobs:
  job1:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout repository
        uses: actions/checkout@v4
      - name: Setup Node lts
        uses: actions/setup-node@v4
        with: 
          node-version: 'lts/*'
      - name:  npm install
        run : npm install
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps: 
      - name: checkout repository
        uses: actions/checkout@v4
      - name: Setup Node lts
        uses: actions/setup-node@v4
        with: 
          node-version: 'lts/*'
      - name:  npm test
        #run:  npm install && npm test
        #multiple string
        run: |  
          npm install
          npm test
           
