name: interact with Github API
on: 
  pull_request:

jobs:
  create-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Short SHA
        id: short_sha
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT # en reference a cette ligne: steps.short_sha.outputs.SHORT_SHA

      - name: Create Issue
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/issues \
          --header 'authorization: Bearer ${{ secrets.MY_PAT }}' \
          --header 'content-type: application/json' \
          --data '{
            "title": "Automated issue for commit: ${{ steps.short_sha.outputs.SHORT_SHA }}", 
            "body": "This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n The commit hash was: _${{ steps.short_sha.outputs.SHORT_SHA }}_."
            }' \
          --fail

