name: Switch Node version
on: 
  pull_request:

jobs:
  run-npm-test:
    runs-on: ubuntu-latest
    steps:
        - env:
           NODEJS_VERSION: 14
        - name: checkout
          uses: actions/checkout@v3
        - name : setup node
          uses: actions/setup-node@v3
          with:
            node-version: ${{env.NODEJS_VERSION}}
        - name: verify node-version 
          run: |
            node -v
        - name: run test
          shell: bash
          run: |
            npm install
            npm test
            
